/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export enum SubscriptionStatus {
  Active = 'active',
  Canceled = 'canceled',
  PastDue = 'past_due',
  Trialing = 'trialing',
}

export enum SubscriptionTier {
  Enterprise = 'enterprise',
  Free = 'free',
  Pro = 'pro',
  Starter = 'starter',
}

export enum TtsJobStatus {
  Done = 'done',
  Failed = 'failed',
  Processing = 'processing',
  Queued = 'queued',
}

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  key_hash: string;
  label: Generated<string>;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface Subscriptions {
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  id: Generated<string>;
  status: Generated<SubscriptionStatus>;
  stripe_customer_id: string;
  stripe_subscription_id: string | null;
  tier: Generated<SubscriptionTier>;
  user_id: string;
}

export interface TtsJobs {
  api_key_id: string;
  audio_url: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  input_text: string;
  status: Generated<TtsJobStatus>;
  user_id: string;
}

export interface UsageRecords {
  billing_period_start: Timestamp;
  characters_used: Generated<Int8>;
  id: Generated<string>;
  requests_count: Generated<number>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  password_hash: string;
}

export interface DB {
  api_keys: ApiKeys;
  subscriptions: Subscriptions;
  tts_jobs: TtsJobs;
  usage_records: UsageRecords;
  users: Users;
}
